#!/bin/bash
dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=/dev/null
source "$dir"/_common
"$dir"/openqa-monitor-investigation-candidates | "$dir"/openqa-label-known-issues-multi 3>&1 1> /dev/null 2>&3- | extract_unreviewed_urls | "$dir"/openqa-investigate-multi
